#!/usr/bin/env perl
#----------------------------------------------------------------------
# gen_wire_inventory.pl
#----------------------------------------------------------------------
#
# Regenerates tests/generated/WireInventory.inc from every packet factory
# declared under Client/Packet/{Gpackets,Cpackets,Lpackets,Upackets}.
#
# Why a generator and not the factories themselves: a factory's vtable
# references createPacket(), which references the packet's constructor
# and vtable, which live in the packet's .cpp beside its handler - and
# the handlers reach into the whole game executable, which no test
# binary can link (see tests/CMakeLists.txt). So instead of instantiating
# GCMoveOKFactory, this script lifts the BODIES of its getPacketID() and
# getPacketMaxSize() verbatim into a plain struct with two static
# functions. The compiler evaluates them against the real sz* constants
# and Packet::PACKET_* ids from the real headers; nothing is linked.
#
# The server repo keeps the same inventory (server/tests/wire-layout.txt,
# produced from its compiled factories). The two files are meant to be
# diffed: server/tests/tools/wire_inventory_diff.sh does that.
#
# Usage (from the repository root):
#     perl tests/tools/gen_wire_inventory.pl [output-path]
#
# The output is committed. tests/unit/test_wire_layout.cpp compiles it;
# the wire_inventory_fresh ctest fails when it drifts from this script.
#
#----------------------------------------------------------------------
use strict;
use warnings;

my $root = 'Client/Packet';
my $out  = $ARGV[0] // 'tests/generated/WireInventory.inc';   # ctest passes a scratch path
-d $root or die "run from the repository root\n";

my @dirs = qw(Gpackets Cpackets Lpackets Upackets);

#----------------------------------------------------------------------
# Pass 1: collect every factory class with its base and method bodies.
#----------------------------------------------------------------------
my %factory;   # name => { base, file, id, size }
my @order;

for my $dir (@dirs) {
	opendir(my $dh, "$root/$dir") or die "$root/$dir: $!";
	for my $h (sort grep { /\.h$/ } readdir $dh) {
		my $path = "$root/$dir/$h";
		open(my $fh, '<', $path) or die "$path: $!";
		local $/;
		my $src = <$fh>;
		close $fh;

		# Strip comments so a commented-out factory or method is not picked up.
		$src =~ s{/\*.*?\*/}{}gs;
		$src =~ s{//[^\n]*}{}g;

		while ($src =~ /class\s+(\w+Factory)\s*:\s*public\s+(\w+)\s*(\{(?:[^{}]|(?3))*\})/g) {
			my ($name, $base, $body) = ($1, $2, $3);
			my ($id)   = $body =~ /getPacketID\s*\(\s*\)\s*const\s*(?:throw\s*\(\s*\))?\s*(\{(?:[^{}]|(?1))*\})/;
			my ($size) = $body =~ /getPacketMaxSize\s*\(\s*\)\s*const\s*(?:throw\s*\(\s*\))?\s*(\{(?:[^{}]|(?1))*\})/;
			die "$path: $name declared twice\n" if exists $factory{$name};
			$factory{$name} = { base => $base, file => "$dir/$h", id => $id, size => $size };
			push @order, $name;
		}
	}
	closedir $dh;
}

#----------------------------------------------------------------------
# Pass 2: resolve inherited methods, rewrite calls to another factory's
# getPacketMaxSize() (a derived factory adding to its base's size) so
# they land on the generated twin, and emit.
#----------------------------------------------------------------------
sub resolve {
	my ($name, $what) = @_;
	my $cur = $name;
	while (1) {
		my $f = $factory{$cur} or die "$name: cannot resolve $what through unknown base $cur\n";
		return $f->{$what} if defined $f->{$what};
		$cur = $f->{base};
		die "$name: no $what in its factory chain\n" if $cur eq 'PacketFactory';
	}
}

sub rewrite {
	my ($body) = @_;
	$body =~ s/\b(\w+Factory)::getPacketMaxSize\s*\(\s*\)/Inv_$1::maxSize()/g;
	$body =~ s/\r//g;
	return $body;
}

my %files;
my @entries;
for my $name (@order) {
	my $f = $factory{$name};
	(my $packet = $name) =~ s/Factory$//;
	$files{ $f->{file} } = 1;
	my $id   = rewrite(resolve($name, 'id'));
	my $size = rewrite(resolve($name, 'size'));
	push @entries, [ $packet, $name, $id, $size ];
}

open(my $o, '>', $out) or die "$out: $!";
binmode $o;
print $o "// Generated by tests/tools/gen_wire_inventory.pl -- DO NOT EDIT BY HAND.\n";
print $o "// Regenerate after adding or changing a packet factory under Client/Packet;\n";
print $o "// the wire_inventory_fresh ctest pins this file against a fresh generation.\n";
print $o "#ifdef WIRE_INVENTORY_INCLUDES\n";
print $o "#include \"$_\"\n" for sort keys %files;
print $o "#endif // WIRE_INVENTORY_INCLUDES\n";
print $o "#ifdef WIRE_INVENTORY_STRUCTS\n";
for my $e (@entries) {
	my ($packet, $name, $id, $size) = @$e;
	print $o "struct Inv_$name {\n";
	print $o "\tstatic PacketID_t id() $id\n";
	print $o "\tstatic PacketSize_t maxSize() $size\n";
	print $o "};\n";
}
print $o "#endif // WIRE_INVENTORY_STRUCTS\n";
print $o "#ifdef WIRE_INVENTORY_ENTRIES\n";
for my $e (@entries) {
	my ($packet, $name) = @$e;
	print $o "\t{ \"$packet\", &Inv_$name\::id, &Inv_$name\::maxSize },\n";
}
print $o "#endif // WIRE_INVENTORY_ENTRIES\n";
close $o;

printf "wrote %s (%d factories from %d headers)\n", $out, scalar @entries, scalar keys %files;
