#!/usr/bin/env perl
#----------------------------------------------------------------------
# gen_wire_inventory.pl
#----------------------------------------------------------------------
#
# Regenerates tests/generated/WireInventory.inc: one include and one
# registration per packet factory declared under
# Client/Packet/{Gpackets,Cpackets,Lpackets,Upackets,Rpackets}, for
# tests/unit/test_wire_layout.cpp to construct the REAL factories with.
#
# Until docs/RESTRUCTURING.md task 2.5 this script lifted the bodies of
# each factory's getPacketID()/getPacketMaxSize() into plain structs,
# because the packet .cpp files compiled only into the game executable
# and no test binary could link a factory. Since task 2.4 they compile
# into the packetwire library, so the inventory is now measured on the
# factory objects themselves - the same registry shape as the server's
# tests/generated/AllPacketFactories.inc.
#
# Rpackets (CR*/RC*, the ranger/remote-admin relics) are registered here
# but flagged OUT of the inventory file: the server deleted its copies,
# and tests/wire-layout.txt is diffed against the server's line for line
# (server/tests/tools/wire_inventory_diff.sh). They are still
# constructed, so their link and the factory manager's registration of
# them are checked like everyone else's.
#
# Usage (from the repository root):
#     perl tests/tools/gen_wire_inventory.pl [output-path]
#
# The output is committed. The wire_inventory_fresh ctest fails when it
# drifts from this script's output.
#
#----------------------------------------------------------------------
use strict;
use warnings;

my $root = 'Client/Packet';
my $out  = $ARGV[0] // 'tests/generated/WireInventory.inc';   # ctest passes a scratch path
-d $root or die "run from the repository root\n";

# Directory => whether its factories belong in tests/wire-layout.txt.
my @dirs = (
	[ Gpackets => 1 ],
	[ Cpackets => 1 ],
	[ Lpackets => 1 ],
	[ Upackets => 1 ],
	[ Rpackets => 0 ],
);

my @entries;   # [ packet, factory, file, inventoried ]
my %seen;

for my $spec (@dirs) {
	my ($dir, $inventoried) = @$spec;
	opendir(my $dh, "$root/$dir") or die "$root/$dir: $!";
	for my $h (sort grep { /\.h$/ } readdir $dh) {
		my $path = "$root/$dir/$h";
		open(my $fh, '<', $path) or die "$path: $!";
		local $/;
		my $src = <$fh>;
		close $fh;

		# Strip comments so a commented-out factory is not picked up.
		$src =~ s{/\*.*?\*/}{}gs;
		$src =~ s{//[^\n]*}{}g;

		while ($src =~ /class\s+(\w+Factory)\s*:\s*public\s+(\w+)\s*(\{(?:[^{}]|(?3))*\})/g) {
			my ($name, $body) = ($1, $3);
			(my $packet = $name) =~ s/Factory$//;
			die "$path: $name declared twice\n" if $seen{$name}++;

			# The inventory names the packet after its factory class;
			# the server names it from getPacketName(). The two must
			# agree or the inventories would not diff line for line.
			if ($body =~ /getPacketName\s*\(\s*\)\s*const\s*(?:throw\s*\(\s*\))?\s*\{\s*return\s*"([^"]*)"/
			    && $1 ne $packet) {
				die "$path: $name says getPacketName() is \"$1\", not $packet\n";
			}
			push @entries, [ $packet, $name, "$dir/$h", $inventoried ];
		}
	}
	closedir $dh;
}

my %files = map { $_->[2] => 1 } @entries;

open(my $o, '>', $out) or die "$out: $!";
binmode $o;
print $o "// Generated by tests/tools/gen_wire_inventory.pl -- DO NOT EDIT BY HAND.\n";
print $o "// Regenerate after adding or changing a packet factory under Client/Packet;\n";
print $o "// the wire_inventory_fresh ctest pins this file against a fresh generation.\n";
print $o "#ifdef WIRE_INVENTORY_INCLUDES\n";
print $o "#include \"$_\"\n" for sort keys %files;
print $o "#endif // WIRE_INVENTORY_INCLUDES\n";
print $o "#ifdef WIRE_INVENTORY_ENTRIES\n";
for my $e (@entries) {
	my ($packet, $name, undef, $inventoried) = @$e;
	printf $o "\tfactories.push_back(FactoryEntry(\"%s\", new %s(), %s));\n",
		$packet, $name, $inventoried ? 'true' : 'false';
}
print $o "#endif // WIRE_INVENTORY_ENTRIES\n";
close $o;

my $inventoried = grep { $_->[3] } @entries;
printf "wrote %s (%d factories from %d headers, %d in the inventory)\n",
	$out, scalar @entries, scalar keys %files, $inventoried;
