//----------------------------------------------------------------------
// test_wire_layout.cpp
//----------------------------------------------------------------------
//
// Wire-layout inventory: packet id, name and max body size for every
// packet factory under Client/Packet, regenerated on each run and
// compared to the committed tests/wire-layout.txt.
//
// The server repo (../server) produces the identical file from its own
// packet classes, and this client carries a hand-maintained copy of
// every one of them. The two inventories are the first mechanical
// check that the copies still agree; server/tests/tools/
// wire_inventory_diff.sh diffs them. A change in this file is a
// wire-protocol change: it must ship in both repos together.
//
// The factories are not instantiated (their vtables would drag every
// packet handler, and so the whole game, into the link). tests/tools/
// gen_wire_inventory.pl lifts each factory's getPacketID() and
// getPacketMaxSize() bodies into tests/generated/WireInventory.inc,
// which this file compiles against the real packet headers.
//
// Set UPDATE_GOLDENS=1 in the environment to re-record the inventory
// instead of comparing.
//
//----------------------------------------------------------------------

#include "test_framework.h"

#include "Packet.h"
#include "PacketFactory.h"

#define WIRE_INVENTORY_INCLUDES
#include "WireInventory.inc"
#undef WIRE_INVENTORY_INCLUDES

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace {

#define WIRE_INVENTORY_STRUCTS
#include "WireInventory.inc"
#undef WIRE_INVENTORY_STRUCTS

struct FactoryEntry
{
	const char*	name;
	PacketID_t	(*id)();
	PacketSize_t	(*maxSize)();
};

const FactoryEntry kFactories[] = {
#define WIRE_INVENTORY_ENTRIES
#include "WireInventory.inc"
#undef WIRE_INVENTORY_ENTRIES
};

const size_t kFactoryCount = sizeof(kFactories) / sizeof(kFactories[0]);

struct InventoryEntry
{
	std::string	name;
	PacketSize_t	maxSize;
};

//----------------------------------------------------------------------
// Same rendering as server/tests/wire_layout_test.cpp, so the two files
// diff line for line.
//----------------------------------------------------------------------
std::map<PacketID_t, InventoryEntry>	BuildInventory(std::vector<std::string>& idConflicts)
{
	std::map<PacketID_t, InventoryEntry> inventory;
	for (size_t i = 0; i < kFactoryCount; i++)
	{
		const PacketID_t id = kFactories[i].id();
		InventoryEntry entry;
		entry.name = kFactories[i].name;
		entry.maxSize = kFactories[i].maxSize();

		std::map<PacketID_t, InventoryEntry>::iterator existing = inventory.find(id);
		if (existing != inventory.end())
		{
			if (existing->second.name != entry.name)
			{
				std::ostringstream conflict;
				conflict << "packet ID " << id << " claimed by both "
					 << existing->second.name << " and " << entry.name;
				idConflicts.push_back(conflict.str());
			}
			continue;
		}
		inventory[id] = entry;
	}
	return inventory;
}

std::string	RenderInventory(const std::map<PacketID_t, InventoryEntry>& inventory)
{
	std::ostringstream out;
	out << "# Wire-layout inventory: packet-id<TAB>name<TAB>max-body-size\n";
	out << "# Generated by test_wire_layout (UPDATE_GOLDENS=1 to re-record).\n";
	out << "# A diff in this file is a wire-protocol change: the server repo's\n";
	out << "# packet classes must ship the identical change.\n";
	for (std::map<PacketID_t, InventoryEntry>::const_iterator it = inventory.begin();
	     it != inventory.end(); ++it)
	{
		out << it->first << "\t" << it->second.name << "\t" << it->second.maxSize << "\n";
	}
	return out.str();
}

// True only when UPDATE_GOLDENS is exactly "1", so UPDATE_GOLDENS=0
// compares instead of silently re-recording.
bool	IsRecording()
{
	const char* value = std::getenv("UPDATE_GOLDENS");
	return value != NULL && std::strcmp(value, "1") == 0;
}

// Print the first line that differs, since CHECK cannot show strings.
void	ReportFirstDifference(const std::string& expected, const std::string& actual)
{
	std::istringstream e(expected);
	std::istringstream a(actual);
	std::string el, al;
	int line = 0;
	while (true)
	{
		const bool he = static_cast<bool>(std::getline(e, el));
		const bool ha = static_cast<bool>(std::getline(a, al));
		line++;
		if (!he && !ha)
			return;
		if (he != ha || el != al)
		{
			std::fprintf(stderr,
				"  wire-layout.txt line %d differs:\n    committed: %s\n    actual:    %s\n",
				line, he ? el.c_str() : "<end of file>", ha ? al.c_str() : "<end of file>");
			return;
		}
	}
}

} // namespace

TEST(WireLayout, PacketIdsAreUniqueAcrossAllFactories)
{
	CHECK(kFactoryCount > 0);
	std::vector<std::string> idConflicts;
	BuildInventory(idConflicts);
	for (size_t i = 0; i < idConflicts.size(); i++)
		std::fprintf(stderr, "  %s\n", idConflicts[i].c_str());
	CHECK_EQ(0, idConflicts.size());
}

TEST(WireLayout, InventoryMatchesCommittedFile)
{
	std::vector<std::string> idConflicts;
	const std::string actual = RenderInventory(BuildInventory(idConflicts));

	const char* path = WIRE_LAYOUT_FILE;
	if (IsRecording())
	{
		std::ofstream file(path, std::ios::trunc | std::ios::binary);
		CHECK(file.good());
		file << actual;
		std::printf("recorded %s (%d packets)\n", path, (int)kFactoryCount);
		return;
	}

	std::ifstream file(path, std::ios::binary);
	CHECK(file.good());	// missing: run once with UPDATE_GOLDENS=1 to record
	std::stringstream expected;
	expected << file.rdbuf();
	// Written in binary, read in binary: a CRLF checkout would still
	// differ, which .gitattributes prevents (eol=lf on the file).
	const bool same = expected.str() == actual;
	if (!same)
	{
		std::fprintf(stderr,
			"  the wire-layout inventory drifted from %s - review the diff as a\n"
			"  protocol change (it must ship in the server repo too) and re-record\n"
			"  with UPDATE_GOLDENS=1\n", path);
		ReportFirstDifference(expected.str(), actual);
	}
	CHECK(same);
}
